spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.flyway.enabled=false

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.listener.auto-startup=false

search.infrastructure.kafka.product-event-topic=product-index-events
search.infrastructure.kafka.consumer-group-id=indexer-group-test
search.infrastructure.opensearch.base-url=http://localhost:9200
